import {
  DashboardKPIData,
  ProgramSummary,
  EmployeePaymentSummary,
  CustomerOutstandingSummary,
  LowStockProductSummary,
} from "@/types";

export const mockKPIData: DashboardKPIData = {
  todaysProgramsCount: 2,
  upcomingProgramsCount: 7,
  employeesWorkingToday: 24,
  totalScheduledEmployeesToday: 28,
  pendingPaymentsAmount: 14850.0,
  pendingEmployeePayoutsCount: 6,
  customerOutstandingTotal: 34200.0,
};

export const mockUpcomingPrograms: ProgramSummary[] = [
  {
    id: "prog-1",
    code: "EVT-2026-101",
    title: "Kapoor & Malhotra Royal Wedding Reception",
    customerName: "Rajesh Malhotra",
    customerPhone: "+1 (555) 432-8871",
    type: "WEDDING",
    date: "2026-09-04",
    time: "18:00 - 23:30",
    location: "Grand Ballroom, Marriott Luxury Suites",
    employeesJoined: 18,
    employeesRequired: 20,
    status: "UPCOMING",
    budget: 28500,
  },
  {
    id: "prog-2",
    code: "EVT-2026-102",
    title: "Apex FinTech Annual Gala Dinner",
    customerName: "Sarah Jenkins",
    customerPhone: "+1 (555) 789-2234",
    type: "CORPORATE",
    date: "2026-09-04",
    time: "19:00 - 22:00",
    location: "Skyline Terrace & Lounge, Downtown",
    employeesJoined: 8,
    employeesRequired: 8,
    status: "UPCOMING",
    budget: 14200,
  },
  {
    id: "prog-3",
    code: "EVT-2026-103",
    title: "Aarav 18th Birthday Celebration",
    customerName: "Deepak Sharma",
    customerPhone: "+1 (555) 654-1928",
    type: "BIRTHDAY",
    date: "2026-09-05",
    time: "16:00 - 21:00",
    location: "Palm Grove Banquets, West Ridge",
    employeesJoined: 6,
    employeesRequired: 8,
    status: "UPCOMING",
    budget: 8500,
  },
  {
    id: "prog-4",
    code: "EVT-2026-104",
    title: "Silver Jubilee Anniversary Banquet",
    customerName: "David & Eleanor Vance",
    customerPhone: "+1 (555) 912-3401",
    type: "ANNIVERSARY",
    date: "2026-09-06",
    time: "17:30 - 22:30",
    location: "Heritage Crystal Hall, North Side",
    employeesJoined: 10,
    employeesRequired: 10,
    status: "UPCOMING",
    budget: 16800,
  },
  {
    id: "prog-5",
    code: "EVT-2026-105",
    title: "Global Tech Summit VIP Cocktail & Dinner",
    customerName: "Nexus Ventures Ltd.",
    customerPhone: "+1 (555) 345-6712",
    type: "CORPORATE",
    date: "2026-09-08",
    time: "18:30 - 23:00",
    location: "Metropolis Convention Center, Hall B",
    employeesJoined: 12,
    employeesRequired: 16,
    status: "UPCOMING",
    budget: 32000,
  },
];

export const mockPendingEmployeePayments: EmployeePaymentSummary[] = [
  {
    id: "pay-1",
    payoutNumber: "PAY-2026-041",
    employeeName: "Marcus Sterling",
    employeeDesignation: "Head Banquet Chef",
    programTitle: "Kapoor & Malhotra Wedding (Prep)",
    eventDate: "2026-09-02",
    hoursWorked: 10.5,
    rate: 35,
    amount: 367.5,
    status: "PENDING",
  },
  {
    id: "pay-2",
    payoutNumber: "PAY-2026-042",
    employeeName: "Elena Rostova",
    employeeDesignation: "Lead Service Supervisor",
    programTitle: "BioTech Founders Dinner",
    eventDate: "2026-09-02",
    hoursWorked: 8.0,
    rate: 28,
    amount: 224.0,
    status: "PENDING",
  },
  {
    id: "pay-3",
    payoutNumber: "PAY-2026-043",
    employeeName: "Tariq Mansoor",
    employeeDesignation: "Master Bartender",
    programTitle: "BioTech Founders Dinner",
    eventDate: "2026-09-02",
    hoursWorked: 7.5,
    rate: 26,
    amount: 195.0,
    status: "PENDING",
  },
  {
    id: "pay-4",
    payoutNumber: "PAY-2026-044",
    employeeName: "Chloe Bennett",
    employeeDesignation: "Senior Banquet Server",
    programTitle: "Oakwood Golf Club Invitational",
    eventDate: "2026-09-01",
    hoursWorked: 9.0,
    rate: 22,
    amount: 198.0,
    status: "PENDING",
  },
  {
    id: "pay-5",
    payoutNumber: "PAY-2026-045",
    employeeName: "Devon Reed",
    employeeDesignation: "Logistics & Equipment Handler",
    programTitle: "Oakwood Golf Club Invitational",
    eventDate: "2026-09-01",
    hoursWorked: 8.5,
    rate: 20,
    amount: 170.0,
    status: "PENDING",
  },
];

export const mockCustomerOutstanding: CustomerOutstandingSummary[] = [
  {
    id: "cust-1",
    customerName: "Rajesh Malhotra",
    companyName: "Malhotra Enterprises",
    phone: "+1 (555) 432-8871",
    totalBilled: 28500.0,
    paidAmount: 15000.0,
    outstanding: 13500.0,
    lastInvoiceDate: "2026-08-28",
    status: "OVERDUE",
  },
  {
    id: "cust-2",
    customerName: "Sarah Jenkins",
    companyName: "Apex FinTech Inc.",
    phone: "+1 (555) 789-2234",
    totalBilled: 14200.0,
    paidAmount: 7000.0,
    outstanding: 7200.0,
    lastInvoiceDate: "2026-08-30",
    status: "CURRENT",
  },
  {
    id: "cust-3",
    customerName: "Deepak Sharma",
    phone: "+1 (555) 654-1928",
    totalBilled: 8500.0,
    paidAmount: 4500.0,
    outstanding: 4000.0,
    lastInvoiceDate: "2026-08-31",
    status: "CURRENT",
  },
  {
    id: "cust-4",
    customerName: "David & Eleanor Vance",
    phone: "+1 (555) 912-3401",
    totalBilled: 16800.0,
    paidAmount: 10000.0,
    outstanding: 6800.0,
    lastInvoiceDate: "2026-08-25",
    status: "OVERDUE",
  },
  {
    id: "cust-5",
    customerName: "Nexus Ventures Ltd.",
    companyName: "Nexus Ventures",
    phone: "+1 (555) 345-6712",
    totalBilled: 32000.0,
    paidAmount: 29300.0,
    outstanding: 2700.0,
    lastInvoiceDate: "2026-09-01",
    status: "CURRENT",
  },
];

export const mockLowStockProducts: LowStockProductSummary[] = [
  {
    id: "prod-1",
    code: "RNT-CHF-01",
    name: "Luxury Stainless Roll-Top Chafing Dish (9L)",
    category: "Rental Equipment",
    type: "RENTAL_EQUIPMENT",
    currentStock: 4,
    minStockAlert: 15,
    unit: "units",
  },
  {
    id: "prod-2",
    code: "CAT-ING-42",
    name: "Aged Basmati Royal Reserve Grain",
    category: "Catering Ingredients",
    type: "CATERING_FOOD",
    currentStock: 18,
    minStockAlert: 50,
    unit: "kg",
  },
  {
    id: "prod-3",
    code: "RNT-LIN-12",
    name: "Ivory Satin Round Banquet Table Linens (120\")",
    category: "Rental Equipment",
    type: "RENTAL_EQUIPMENT",
    currentStock: 12,
    minStockAlert: 35,
    unit: "pieces",
  },
  {
    id: "prod-4",
    code: "CAT-ING-88",
    name: "Organic Iranian Saffron Strands",
    category: "Catering Ingredients",
    type: "CATERING_FOOD",
    currentStock: 65,
    minStockAlert: 200,
    unit: "grams",
  },
  {
    id: "prod-5",
    code: "RNT-GLS-08",
    name: "Crystal Champagne Flutes (Pack of 24)",
    category: "Rental Equipment",
    type: "RENTAL_EQUIPMENT",
    currentStock: 3,
    minStockAlert: 12,
    unit: "packs",
  },
];
